### ISSUE TITLE
If you unlock at start the SEED is in plain text and not protected by a password in the BACKUP section

### ISSUE THREAD

**Issue by rdymac** [ExodusMovement/exodus-linux-installer#1]
If you have the wallet opened and you unlock it with your password the SEED can be seen without requesting the password again in the BACKUP section. There is no way to protect the seed without closing the entire app.

I see this on Mac, but can't find a Mac specific section in this GitHub.

**Comment by jprichardson** [comment]
I followed-up via email. Closing this issue since it's not related to the Exodus Linux installer.
