### ISSUE TITLE
Linux app should offer option to create desktop shortcut

### ISSUE THREAD

**Issue by tredondo** [ExodusMovement/exodus-linux-installer#11]
The [Linux app](http://support.exodus.io/article/36-how-do-i-install-exodus) is "portable" (no installation required), which is great, but one downside is that it doesn't install a shortcut.

[On Ubuntu, creating shortcuts is a royal pain.](https://askubuntu.com/questions/64222/how-can-i-create-launchers-on-my-desktop) It would be great if on Linux, Exodus had a mechanism to create a desktop shortcut. WebStorm does this and it works very well.

**Comment by RyanZim** [comment]
Exodus now offers a `.deb` installer for Debian/Ubuntu that will create a shortcut in the applications menu automatically.
