### ISSUE TITLE
Is this still up-to-date?

### ISSUE THREAD

**Issue by dandv** [ExodusMovement/exodus-linux-installer#2]
The script looks for [a tar.xz archive](https://github.com/ExodusMovement/exodus-linux-installer/blob/master/exodus-installer.sh#L7) on dropbox but the current download is https://exodusbin.azureedge.net/releases/exodus_linux_1.23.0.zip

**Comment by fanatid** [comment]
I think this is outdated, we have almost ready solution for linux installer which works with [makeself](https://github.com/megastep/makeself). Can not say nothing about dates unfortunately.
